version: '3'
services:
  ace-db:
    image: mysql:5.7
    container_name: ace-db
    env_file:
      - docker.env
    volumes:
      - ace-db-data:/var/lib/mysql
      - $PWD/Database:/ace/Database
      - $PWD/Scripts/initdb.sh:/docker-entrypoint-initdb.d/1.sh
      - $PWD/Database/Optional/World/ACE-World-Database-v0.9.250.sql.gz:/docker-entrypoint-initdb.d/2.sql.gz
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server:
    build: .
    image: acemulator/ace:latest
    depends_on:
      - ace-db
    container_name: ace-server
    env_file:
      - docker.env
    volumes:
      - ./Dats:/ace/Dats
      - ace-config:/ace/Config
      - ace-content:/ace/Content
      - ace-logs:/ace/Logs
    ports:
      - "9000-9001:9000-9001/udp"
    #restart: unless-stopped

volumes:
  ace-db-data:
  ace-config:
  ace-content:
  ace-dats:
  ace-logs:
